using System.Collections.Generic;

namespace CgfConverter.Models.Shaders;

/// <summary>
/// Represents an interpreted shader rule to apply to a material during USD export.
/// Generated by the ShaderRulesEngine based on active StringGenMask flags.
/// </summary>
public class MaterialRule
{
    /// <summary>The shader property flag that triggered this rule (e.g., "%ALPHAGLOW")</summary>
    public string PropertyName { get; set; } = string.Empty;

    /// <summary>Human-readable description of what this rule does</summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>Rule type/category for processing</summary>
    public RuleType Type { get; set; }

    /// <summary>Which texture map this rule affects (if applicable)</summary>
    public string? SourceTexture { get; set; }

    /// <summary>Which channel from the source texture (e.g., "alpha", "rgb", "r", "g", "b")</summary>
    public string? SourceChannel { get; set; }

    /// <summary>Target input on the material node (e.g., "emissiveColor", "opacity", "roughness")</summary>
    public string? TargetInput { get; set; }

    /// <summary>Additional metadata or parameters for complex rules</summary>
    public Dictionary<string, object>? Metadata { get; set; }

    public override string ToString() => $"{PropertyName}: {Description}";
}

/// <summary>
/// Categories of material rules for processing
/// </summary>
public enum RuleType
{
    /// <summary>Route a texture channel to a material input (e.g., diffuse.alpha → emissive)</summary>
    ChannelRouting,

    /// <summary>Enable a specific texture map (e.g., environment map, gloss map)</summary>
    TextureEnable,

    /// <summary>Enable vertex color usage</summary>
    VertexColors,

    /// <summary>Modify material property or add special handling</summary>
    PropertyModifier,

    /// <summary>Unknown or unsupported rule type</summary>
    Unknown
}
